/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SimpleAssetEscrow {
  export type OrderStruct = {
    buyer: AddressLike;
    seller: AddressLike;
    paymentToken: AddressLike;
    assetTokens: AddressLike[];
    assetAmounts: BigNumberish[];
    paymentAmount: BigNumberish;
    expirationTime: BigNumberish;
    paymentDeposited: boolean;
    assetsDelivered: boolean;
    buyerVerified: boolean;
    sellerVerified: boolean;
    authorityVerified: boolean;
    completed: boolean;
    cancelled: boolean;
  };

  export type OrderStructOutput = [
    buyer: string,
    seller: string,
    paymentToken: string,
    assetTokens: string[],
    assetAmounts: bigint[],
    paymentAmount: bigint,
    expirationTime: bigint,
    paymentDeposited: boolean,
    assetsDelivered: boolean,
    buyerVerified: boolean,
    sellerVerified: boolean,
    authorityVerified: boolean,
    completed: boolean,
    cancelled: boolean
  ] & {
    buyer: string;
    seller: string;
    paymentToken: string;
    assetTokens: string[];
    assetAmounts: bigint[];
    paymentAmount: bigint;
    expirationTime: bigint;
    paymentDeposited: boolean;
    assetsDelivered: boolean;
    buyerVerified: boolean;
    sellerVerified: boolean;
    authorityVerified: boolean;
    completed: boolean;
    cancelled: boolean;
  };
}

export interface SimpleAssetEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelOrder"
      | "centralAuthority"
      | "createOrder"
      | "deliverAssets"
      | "depositPayment"
      | "feeCollector"
      | "feePercentage"
      | "getOrder"
      | "orderCounter"
      | "orders"
      | "owner"
      | "renounceOwnership"
      | "setFeeCollector"
      | "setFeePercentage"
      | "transferOwnership"
      | "verifyOrder"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetsDelivered"
      | "OrderCancelled"
      | "OrderCompleted"
      | "OrderCreated"
      | "OrderVerified"
      | "OwnershipTransferred"
      | "PaymentDeposited"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "centralAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      AddressLike,
      AddressLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deliverAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orderCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyOrder",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "centralAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deliverAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orderCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyOrder",
    data: BytesLike
  ): Result;
}

export namespace AssetsDeliveredEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCompletedEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike
  ];
  export type OutputTuple = [orderId: bigint, buyer: string, seller: string];
  export interface OutputObject {
    orderId: bigint;
    buyer: string;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderVerifiedEvent {
  export type InputTuple = [orderId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [orderId: bigint, verifier: string];
  export interface OutputObject {
    orderId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentDepositedEvent {
  export type InputTuple = [orderId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [orderId: bigint, amount: bigint];
  export interface OutputObject {
    orderId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleAssetEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleAssetEscrow;
  waitForDeployment(): Promise<this>;

  interface: SimpleAssetEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  centralAuthority: TypedContractMethod<[], [string], "view">;

  createOrder: TypedContractMethod<
    [
      seller: AddressLike,
      paymentToken: AddressLike,
      assetTokens: AddressLike[],
      assetAmounts: BigNumberish[],
      paymentAmount: BigNumberish,
      expirationTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deliverAssets: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositPayment: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  feePercentage: TypedContractMethod<[], [bigint], "view">;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [SimpleAssetEscrow.OrderStructOutput],
    "view"
  >;

  orderCounter: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        buyer: string;
        seller: string;
        paymentToken: string;
        paymentAmount: bigint;
        expirationTime: bigint;
        paymentDeposited: boolean;
        assetsDelivered: boolean;
        buyerVerified: boolean;
        sellerVerified: boolean;
        authorityVerified: boolean;
        completed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeCollector: TypedContractMethod<
    [newFeeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeePercentage: TypedContractMethod<
    [newFeePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "centralAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      seller: AddressLike,
      paymentToken: AddressLike,
      assetTokens: AddressLike[],
      assetAmounts: BigNumberish[],
      paymentAmount: BigNumberish,
      expirationTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deliverAssets"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositPayment"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [SimpleAssetEscrow.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "orderCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        buyer: string;
        seller: string;
        paymentToken: string;
        paymentAmount: bigint;
        expirationTime: bigint;
        paymentDeposited: boolean;
        assetsDelivered: boolean;
        buyerVerified: boolean;
        sellerVerified: boolean;
        authorityVerified: boolean;
        completed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[newFeeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeePercentage"
  ): TypedContractMethod<
    [newFeePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AssetsDelivered"
  ): TypedContractEvent<
    AssetsDeliveredEvent.InputTuple,
    AssetsDeliveredEvent.OutputTuple,
    AssetsDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCompleted"
  ): TypedContractEvent<
    OrderCompletedEvent.InputTuple,
    OrderCompletedEvent.OutputTuple,
    OrderCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderVerified"
  ): TypedContractEvent<
    OrderVerifiedEvent.InputTuple,
    OrderVerifiedEvent.OutputTuple,
    OrderVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentDeposited"
  ): TypedContractEvent<
    PaymentDepositedEvent.InputTuple,
    PaymentDepositedEvent.OutputTuple,
    PaymentDepositedEvent.OutputObject
  >;

  filters: {
    "AssetsDelivered(uint256)": TypedContractEvent<
      AssetsDeliveredEvent.InputTuple,
      AssetsDeliveredEvent.OutputTuple,
      AssetsDeliveredEvent.OutputObject
    >;
    AssetsDelivered: TypedContractEvent<
      AssetsDeliveredEvent.InputTuple,
      AssetsDeliveredEvent.OutputTuple,
      AssetsDeliveredEvent.OutputObject
    >;

    "OrderCancelled(uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCompleted(uint256)": TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;
    OrderCompleted: TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderVerified(uint256,address)": TypedContractEvent<
      OrderVerifiedEvent.InputTuple,
      OrderVerifiedEvent.OutputTuple,
      OrderVerifiedEvent.OutputObject
    >;
    OrderVerified: TypedContractEvent<
      OrderVerifiedEvent.InputTuple,
      OrderVerifiedEvent.OutputTuple,
      OrderVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentDeposited(uint256,uint256)": TypedContractEvent<
      PaymentDepositedEvent.InputTuple,
      PaymentDepositedEvent.OutputTuple,
      PaymentDepositedEvent.OutputObject
    >;
    PaymentDeposited: TypedContractEvent<
      PaymentDepositedEvent.InputTuple,
      PaymentDepositedEvent.OutputTuple,
      PaymentDepositedEvent.OutputObject
    >;
  };
}
