/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SimpleCentralAuthority {
  export type AssetVerificationStruct = {
    supplier: AddressLike;
    assetType: string;
    quantity: BigNumberish;
    location: string;
    verificationNotes: string;
    timestamp: BigNumberish;
    verifier: AddressLike;
  };

  export type AssetVerificationStructOutput = [
    supplier: string,
    assetType: string,
    quantity: bigint,
    location: string,
    verificationNotes: string,
    timestamp: bigint,
    verifier: string
  ] & {
    supplier: string;
    assetType: string;
    quantity: bigint;
    location: string;
    verificationNotes: string;
    timestamp: bigint;
    verifier: string;
  };
}

export interface SimpleCentralAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "VERIFIER_ROLE"
      | "approveSupplier"
      | "assetVerifications"
      | "authorizeTokenMinting"
      | "emergencyBurnExpiredTokens"
      | "getAssetVerification"
      | "getRoleAdmin"
      | "getSupplierInfo"
      | "grantRole"
      | "hasRole"
      | "isSupplierApproved"
      | "pause"
      | "paused"
      | "registerSupplier"
      | "registerToken"
      | "registeredTokens"
      | "renounceRole"
      | "revokeRole"
      | "suppliers"
      | "supportsInterface"
      | "unpause"
      | "verificationCounter"
      | "verifyAssetBacking"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetVerified"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SupplierApproved"
      | "SupplierRegistered"
      | "TokenMinted"
      | "TokenRegistered"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveSupplier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assetVerifications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeTokenMinting",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyBurnExpiredTokens",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetVerification",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplierInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupplierApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerSupplier",
    values: [AddressLike, string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerToken",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredTokens",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suppliers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verificationCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAssetBacking",
    values: [AddressLike, string, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeTokenMinting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyBurnExpiredTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplierInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSupplierApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "suppliers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verificationCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAssetBacking",
    data: BytesLike
  ): Result;
}

export namespace AssetVerifiedEvent {
  export type InputTuple = [
    verificationId: BigNumberish,
    supplier: AddressLike,
    assetType: string,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    verificationId: bigint,
    supplier: string,
    assetType: string,
    quantity: bigint
  ];
  export interface OutputObject {
    verificationId: bigint;
    supplier: string;
    assetType: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplierApprovedEvent {
  export type InputTuple = [supplier: AddressLike];
  export type OutputTuple = [supplier: string];
  export interface OutputObject {
    supplier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplierRegisteredEvent {
  export type InputTuple = [supplier: AddressLike, name: string];
  export type OutputTuple = [supplier: string, name: string];
  export interface OutputObject {
    supplier: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenMintedEvent {
  export type InputTuple = [
    token: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, recipient: string, amount: bigint];
  export interface OutputObject {
    token: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRegisteredEvent {
  export type InputTuple = [tokenAddress: AddressLike, assetType: string];
  export type OutputTuple = [tokenAddress: string, assetType: string];
  export interface OutputObject {
    tokenAddress: string;
    assetType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleCentralAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleCentralAuthority;
  waitForDeployment(): Promise<this>;

  interface: SimpleCentralAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  approveSupplier: TypedContractMethod<
    [supplierAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  assetVerifications: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, string] & {
        supplier: string;
        assetType: string;
        quantity: bigint;
        location: string;
        verificationNotes: string;
        timestamp: bigint;
        verifier: string;
      }
    ],
    "view"
  >;

  authorizeTokenMinting: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      createdAt: BigNumberish,
      expiryTimestamp: BigNumberish,
      location: string
    ],
    [void],
    "nonpayable"
  >;

  emergencyBurnExpiredTokens: TypedContractMethod<
    [tokenAddress: AddressLike, holder: AddressLike],
    [void],
    "nonpayable"
  >;

  getAssetVerification: TypedContractMethod<
    [verificationId: BigNumberish],
    [SimpleCentralAuthority.AssetVerificationStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSupplierInfo: TypedContractMethod<
    [supplier: AddressLike],
    [
      [string, string, string[], boolean, bigint] & {
        name: string;
        location: string;
        assetTypes: string[];
        isApproved: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isSupplierApproved: TypedContractMethod<
    [supplier: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerSupplier: TypedContractMethod<
    [
      supplierAddress: AddressLike,
      name: string,
      location: string,
      assetTypes: string[]
    ],
    [void],
    "nonpayable"
  >;

  registerToken: TypedContractMethod<
    [tokenAddress: AddressLike, assetType: string],
    [void],
    "nonpayable"
  >;

  registeredTokens: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [string],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  suppliers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        location: string;
        isApproved: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verificationCounter: TypedContractMethod<[], [bigint], "view">;

  verifyAssetBacking: TypedContractMethod<
    [
      supplier: AddressLike,
      assetType: string,
      quantity: BigNumberish,
      location: string,
      verificationNotes: string
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveSupplier"
  ): TypedContractMethod<[supplierAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assetVerifications"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, string] & {
        supplier: string;
        assetType: string;
        quantity: bigint;
        location: string;
        verificationNotes: string;
        timestamp: bigint;
        verifier: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeTokenMinting"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      createdAt: BigNumberish,
      expiryTimestamp: BigNumberish,
      location: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyBurnExpiredTokens"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, holder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAssetVerification"
  ): TypedContractMethod<
    [verificationId: BigNumberish],
    [SimpleCentralAuthority.AssetVerificationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSupplierInfo"
  ): TypedContractMethod<
    [supplier: AddressLike],
    [
      [string, string, string[], boolean, bigint] & {
        name: string;
        location: string;
        assetTypes: string[];
        isApproved: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSupplierApproved"
  ): TypedContractMethod<[supplier: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerSupplier"
  ): TypedContractMethod<
    [
      supplierAddress: AddressLike,
      name: string,
      location: string,
      assetTypes: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerToken"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, assetType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredTokens"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "suppliers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        location: string;
        isApproved: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyAssetBacking"
  ): TypedContractMethod<
    [
      supplier: AddressLike,
      assetType: string,
      quantity: BigNumberish,
      location: string,
      verificationNotes: string
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "AssetVerified"
  ): TypedContractEvent<
    AssetVerifiedEvent.InputTuple,
    AssetVerifiedEvent.OutputTuple,
    AssetVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SupplierApproved"
  ): TypedContractEvent<
    SupplierApprovedEvent.InputTuple,
    SupplierApprovedEvent.OutputTuple,
    SupplierApprovedEvent.OutputObject
  >;
  getEvent(
    key: "SupplierRegistered"
  ): TypedContractEvent<
    SupplierRegisteredEvent.InputTuple,
    SupplierRegisteredEvent.OutputTuple,
    SupplierRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "TokenMinted"
  ): TypedContractEvent<
    TokenMintedEvent.InputTuple,
    TokenMintedEvent.OutputTuple,
    TokenMintedEvent.OutputObject
  >;
  getEvent(
    key: "TokenRegistered"
  ): TypedContractEvent<
    TokenRegisteredEvent.InputTuple,
    TokenRegisteredEvent.OutputTuple,
    TokenRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AssetVerified(uint256,address,string,uint256)": TypedContractEvent<
      AssetVerifiedEvent.InputTuple,
      AssetVerifiedEvent.OutputTuple,
      AssetVerifiedEvent.OutputObject
    >;
    AssetVerified: TypedContractEvent<
      AssetVerifiedEvent.InputTuple,
      AssetVerifiedEvent.OutputTuple,
      AssetVerifiedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SupplierApproved(address)": TypedContractEvent<
      SupplierApprovedEvent.InputTuple,
      SupplierApprovedEvent.OutputTuple,
      SupplierApprovedEvent.OutputObject
    >;
    SupplierApproved: TypedContractEvent<
      SupplierApprovedEvent.InputTuple,
      SupplierApprovedEvent.OutputTuple,
      SupplierApprovedEvent.OutputObject
    >;

    "SupplierRegistered(address,string)": TypedContractEvent<
      SupplierRegisteredEvent.InputTuple,
      SupplierRegisteredEvent.OutputTuple,
      SupplierRegisteredEvent.OutputObject
    >;
    SupplierRegistered: TypedContractEvent<
      SupplierRegisteredEvent.InputTuple,
      SupplierRegisteredEvent.OutputTuple,
      SupplierRegisteredEvent.OutputObject
    >;

    "TokenMinted(address,address,uint256)": TypedContractEvent<
      TokenMintedEvent.InputTuple,
      TokenMintedEvent.OutputTuple,
      TokenMintedEvent.OutputObject
    >;
    TokenMinted: TypedContractEvent<
      TokenMintedEvent.InputTuple,
      TokenMintedEvent.OutputTuple,
      TokenMintedEvent.OutputObject
    >;

    "TokenRegistered(address,string)": TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;
    TokenRegistered: TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
