/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEscrow {
  export type OrderStruct = {
    orderId: BigNumberish;
    buyer: AddressLike;
    seller: AddressLike;
    paymentToken: AddressLike;
    assetTokens: AddressLike[];
    assetAmounts: BigNumberish[];
    paymentAmount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
    buyerVerified: boolean;
    sellerVerified: boolean;
    authorityVerified: boolean;
  };

  export type OrderStructOutput = [
    orderId: bigint,
    buyer: string,
    seller: string,
    paymentToken: string,
    assetTokens: string[],
    assetAmounts: bigint[],
    paymentAmount: bigint,
    status: bigint,
    createdAt: bigint,
    expiresAt: bigint,
    buyerVerified: boolean,
    sellerVerified: boolean,
    authorityVerified: boolean
  ] & {
    orderId: bigint;
    buyer: string;
    seller: string;
    paymentToken: string;
    assetTokens: string[];
    assetAmounts: bigint[];
    paymentAmount: bigint;
    status: bigint;
    createdAt: bigint;
    expiresAt: bigint;
    buyerVerified: boolean;
    sellerVerified: boolean;
    authorityVerified: boolean;
  };
}

export interface IEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelOrder"
      | "completeOrder"
      | "createOrder"
      | "deliverAssets"
      | "depositPayment"
      | "getOrder"
      | "getOrderCount"
      | "verifyOrder"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetsDelivered"
      | "OrderCancelled"
      | "OrderCompleted"
      | "OrderCreated"
      | "OrderVerified"
      | "PaymentDeposited"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      AddressLike,
      AddressLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deliverAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyOrder",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deliverAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyOrder",
    data: BytesLike
  ): Result;
}

export namespace AssetsDeliveredEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCompletedEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    paymentAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    buyer: string,
    seller: string,
    paymentAmount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    buyer: string;
    seller: string;
    paymentAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderVerifiedEvent {
  export type InputTuple = [orderId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [orderId: bigint, verifier: string];
  export interface OutputObject {
    orderId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentDepositedEvent {
  export type InputTuple = [orderId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [orderId: bigint, amount: bigint];
  export interface OutputObject {
    orderId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IEscrow;
  waitForDeployment(): Promise<this>;

  interface: IEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [
      seller: AddressLike,
      paymentToken: AddressLike,
      assetTokens: AddressLike[],
      assetAmounts: BigNumberish[],
      paymentAmount: BigNumberish,
      expirationTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deliverAssets: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositPayment: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [IEscrow.OrderStructOutput],
    "view"
  >;

  getOrderCount: TypedContractMethod<[], [bigint], "view">;

  verifyOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      seller: AddressLike,
      paymentToken: AddressLike,
      assetTokens: AddressLike[],
      assetAmounts: BigNumberish[],
      paymentAmount: BigNumberish,
      expirationTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deliverAssets"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositPayment"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [IEscrow.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AssetsDelivered"
  ): TypedContractEvent<
    AssetsDeliveredEvent.InputTuple,
    AssetsDeliveredEvent.OutputTuple,
    AssetsDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCompleted"
  ): TypedContractEvent<
    OrderCompletedEvent.InputTuple,
    OrderCompletedEvent.OutputTuple,
    OrderCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderVerified"
  ): TypedContractEvent<
    OrderVerifiedEvent.InputTuple,
    OrderVerifiedEvent.OutputTuple,
    OrderVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentDeposited"
  ): TypedContractEvent<
    PaymentDepositedEvent.InputTuple,
    PaymentDepositedEvent.OutputTuple,
    PaymentDepositedEvent.OutputObject
  >;

  filters: {
    "AssetsDelivered(uint256)": TypedContractEvent<
      AssetsDeliveredEvent.InputTuple,
      AssetsDeliveredEvent.OutputTuple,
      AssetsDeliveredEvent.OutputObject
    >;
    AssetsDelivered: TypedContractEvent<
      AssetsDeliveredEvent.InputTuple,
      AssetsDeliveredEvent.OutputTuple,
      AssetsDeliveredEvent.OutputObject
    >;

    "OrderCancelled(uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCompleted(uint256)": TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;
    OrderCompleted: TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderVerified(uint256,address)": TypedContractEvent<
      OrderVerifiedEvent.InputTuple,
      OrderVerifiedEvent.OutputTuple,
      OrderVerifiedEvent.OutputObject
    >;
    OrderVerified: TypedContractEvent<
      OrderVerifiedEvent.InputTuple,
      OrderVerifiedEvent.OutputTuple,
      OrderVerifiedEvent.OutputObject
    >;

    "PaymentDeposited(uint256,uint256)": TypedContractEvent<
      PaymentDepositedEvent.InputTuple,
      PaymentDepositedEvent.OutputTuple,
      PaymentDepositedEvent.OutputObject
    >;
    PaymentDeposited: TypedContractEvent<
      PaymentDepositedEvent.InputTuple,
      PaymentDepositedEvent.OutputTuple,
      PaymentDepositedEvent.OutputObject
    >;
  };
}
