/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IClaimTopicsRegistry } from "./IClaimTopicsRegistry";
export type { ICompliance } from "./ICompliance";
export type { IERC3643 } from "./IERC3643";
export type { IEscrow } from "./IEscrow";
export type { IIdentityRegistry } from "./IIdentityRegistry";
export type { ITrustedIssuersRegistry } from "./ITrustedIssuersRegistry";
