/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IClaimTopicsRegistry__factory } from "./IClaimTopicsRegistry__factory";
export { ICompliance__factory } from "./ICompliance__factory";
export { IERC3643__factory } from "./IERC3643__factory";
export { IEscrow__factory } from "./IEscrow__factory";
export { IIdentityRegistry__factory } from "./IIdentityRegistry__factory";
export { ITrustedIssuersRegistry__factory } from "./ITrustedIssuersRegistry__factory";
