/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockOnchainIDInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addClaim"
      | "addKey"
      | "claims"
      | "getClaim"
      | "getClaimIdsByTopic"
      | "keyHasPurpose"
      | "owner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addClaim",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addKey",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaim",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimIdsByTopic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "keyHasPurpose",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimIdsByTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keyHasPurpose",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
}

export interface MockOnchainID extends BaseContract {
  connect(runner?: ContractRunner | null): MockOnchainID;
  waitForDeployment(): Promise<this>;

  interface: MockOnchainIDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addClaim: TypedContractMethod<
    [
      _topic: BigNumberish,
      _scheme: BigNumberish,
      _issuer: AddressLike,
      _signature: BytesLike,
      _data: BytesLike,
      _uri: string
    ],
    [boolean],
    "nonpayable"
  >;

  addKey: TypedContractMethod<
    [_key: BytesLike, _purpose: BigNumberish, _keyType: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  claims: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  getClaim: TypedContractMethod<
    [_topic: BigNumberish, _issuer: AddressLike],
    [string],
    "view"
  >;

  getClaimIdsByTopic: TypedContractMethod<
    [_topic: BigNumberish],
    [string[]],
    "view"
  >;

  keyHasPurpose: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addClaim"
  ): TypedContractMethod<
    [
      _topic: BigNumberish,
      _scheme: BigNumberish,
      _issuer: AddressLike,
      _signature: BytesLike,
      _data: BytesLike,
      _uri: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addKey"
  ): TypedContractMethod<
    [_key: BytesLike, _purpose: BigNumberish, _keyType: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaim"
  ): TypedContractMethod<
    [_topic: BigNumberish, _issuer: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimIdsByTopic"
  ): TypedContractMethod<[_topic: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "keyHasPurpose"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
